In [ ]:
import pandas as pd

In [ ]:
fp = r"C:\Users\Priya\Downloads\project\traffic_stops.xlsx"

In [ ]:
import pandas as pd

df = pd.read_excel("traffic_stops.xlsx")
print(df.head())

    stop_date stop_time country_name driver_gender  driver_age_raw  \
0  01-01-2020  00:00:00       Canada             M              59
1  01-01-2020  00:01:00        India             M              35
2  01-01-2020  00:02:00          USA             M              26
3  01-01-2020  00:03:00       Canada             M              26
4  01-01-2020  00:04:00       Canada             M              62

   driver_age driver_race     violation_raw violation  search_conducted  \
0          19       Asian     Drunk Driving  Speeding              True
1          58       Other             Other     Other             False
2          76       Black  Signal Violation  Speeding             False
3          76       Black          Speeding       DUI              True
4          75       Other          Speeding     Other             False

      search_type stop_outcome  is_arrested stop_duration  drugs_related_stop  \
0  Vehicle Search       Ticket         True     16-30 Min                True
1  Vehicle Search       Arrest         True     16-30 Min                True
2           Frisk       Ticket         True     16-30 Min                True
3           Frisk      Warning        False      0-15 Min                True
4  Vehicle Search       Arrest         True     16-30 Min               False

  vehicle_number
0     UP76DY3473
1     RJ83PZ4441
2     RJ32OM7264
3     RJ76TI3807
4     WB63BB8305

In [ ]:
#to check if there is any null values
#isnull will check whether the data has null values,sum will count the number of values
print(df.isnull().sum())

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64

In [ ]:
#filling the none values with the word 'Not Searched'
df['search_type']=df['search_type'].fillna("Not Searched")

***Dataset Explanation***

stop_date – The date when the stop happened.
stop_time – The time of the stop.
country_name – The country where the stop took place.
driver_gender – The gender of the driver (Male or Female).
driver_age_raw – The recorded age of the driver (before cleaning).
driver_age – The actual age of the driver (after cleaning).
driver_race – The race/ethnicity of the driver.
violation_raw – The original reason for the stop (before cleaning).
violation – The type of violation (Speeding, DUI, etc.).
search_conducted – Whether the police searched the driver or vehicle
search_type – The type of search (Frisk, Vehicle Search, etc.).
stop_outcome – The result of the stop (Warning, Citation, Arrest).
is_arrested – Whether the driver was arrested (True/False).
stop_duration – How long the stop lasted (<5 min, 6-15 min, etc.).
drugs_related_stop – Whether the stop was drug-related (True/False)

In [ ]:
#there is no null values
df.isnull().sum()

stop_date             0
stop_time             0
country_name          0
driver_gender         0
driver_age_raw        0
driver_age            0
driver_race           0
violation_raw         0
violation             0
search_conducted      0
search_type           0
stop_outcome          0
is_arrested           0
stop_duration         0
drugs_related_stop    0
vehicle_number        0
dtype: int64

In [ ]:
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,01-01-2020,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,01-01-2020,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,01-01-2020,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,01-01-2020,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,01-01-2020,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,15-02-2020,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,15-02-2020,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,15-02-2020,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,15-02-2020,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,Not Searched,Warning,True,0-15 Min,True,KA24UZ8488
65537,15-02-2020,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,Not Searched,Ticket,True,16-30 Min,False,UP89PT2924

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  object
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         65538 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), int64(2), object(11)
memory usage: 6.7+ MB

In [ ]:
from datetime import datetime
now_time=datetime.now().time()
print(now_time)

17:11:19.392693

In [ ]:
#to convert the datatype(object) to datetime
df['stop_time'] = pd.to_datetime(df['stop_time'], format='%H:%M:%S', errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  object
 1   stop_time           65538 non-null  datetime64[ns]
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         65538 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), datetime64[ns](1), int64(2), object(10)
memory usage: 6.7+ MB

In [ ]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.12/dist-packages (9.5.0)

In [ ]:
import mysql.connector
print("MySQL connector installed successfully!")

In [ ]:
#Connecting MySQL server
import mysql.connector

In [ ]:
import pandas as pd

traffic_stops = pd.read_excel("traffic_stops.xlsx")

traffic_stops.shape

(65538, 16)

**Descriptive Statistics of the Dataset**

In [ ]:
#Numerical analysis

traffic_stops.describe()

       driver_age_raw   driver_age
count    65538.000000  65538.00000
mean        49.055998     49.11221
std         18.174699     18.15012
min         18.000000     18.00000
25%         33.000000     34.00000
50%         49.000000     49.00000
75%         65.000000     65.00000
max         80.000000     80.00000

In [ ]:
#object

traffic_stops['country_name'].describe()

count     65538
unique        3
top       India
freq      21998
Name: country_name, dtype: object

Accessing column wise

In [ ]:
traffic_stops['country_name']

0        Canada
1         India
2           USA
3        Canada
4        Canada
          ...
65533     India
65534    Canada
65535       USA
65536    Canada
65537       USA
Name: country_name, Length: 65538, dtype: object

In [ ]:
type(traffic_stops['country_name'])

In [ ]:
traffic_stops[['driver_gender','driver_age']]

      driver_gender  driver_age
0                 M          19
1                 M          58
2                 M          76
3                 M          76
4                 M          75
...             ...         ...
65533             F          48
65534             F          35
65535             M          41
65536             F          63
65537             F          32

[65538 rows x 2 columns]

In [ ]:

traffic_stops.iloc[:,2]

0        Canada
1         India
2           USA
3        Canada
4        Canada
          ...
65533     India
65534    Canada
65535       USA
65536    Canada
65537       USA
Name: country_name, Length: 65538, dtype: object

In [ ]:
#Display specified row and column

traffic_stops.iloc[[345,234,567,2345,3455],[0,1,11,12]]

       stop_date stop_time stop_outcome  is_arrested
345   01-01-2020  05:45:00       Ticket        False
234   01-01-2020  03:54:00      Warning        False
567   01-01-2020  09:27:00       Arrest         True
2345  02-01-2020  15:05:00      Warning         True
3455  03-01-2020  09:35:00       Arrest         True

In [ ]:
#Display sequence of row and column
traffic_stops.iloc[3456:4442, :]

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
3456,03-01-2020,09:36:00,India,F,52,62,Black,Seatbelt,DUI,True,Vehicle Search,Arrest,True,0-15 Min,False,TN13TV3266
3457,03-01-2020,09:37:00,Canada,F,41,35,Other,Signal Violation,DUI,False,Frisk,Warning,False,0-15 Min,False,TN72MV4003
3458,03-01-2020,09:38:00,India,F,41,45,Hispanic,Seatbelt,Other,True,NaN,Warning,False,16-30 Min,True,RJ64DB7523
3459,03-01-2020,09:39:00,Canada,M,74,19,Asian,Seatbelt,Other,True,NaN,Arrest,True,30+ Min,True,GJ83JF1610
3460,03-01-2020,09:40:00,USA,F,67,21,Asian,Seatbelt,Speeding,False,NaN,Arrest,True,30+ Min,False,UP62YO3732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4437,04-01-2020,01:57:00,USA,M,39,70,Black,Signal Violation,Speeding,False,NaN,Ticket,False,16-30 Min,True,UP27RF8873
4438,04-01-2020,01:58:00,India,M,19,36,Black,Speeding,Speeding,False,Vehicle Search,Warning,False,30+ Min,False,MH71UM4746
4439,04-01-2020,01:59:00,India,F,30,29,Other,Seatbelt,Seatbelt,True,NaN,Warning,True,30+ Min,True,UP53KP8374
4440,04-01-2020,02:00:00,USA,F,63,19,Other,Signal Violation,Seatbelt,False,NaN,Arrest,True,30+ Min,True,WB72LV6330
4441,04-01-2020,02:01:00,USA,F,69,39,Black,Speeding,Signal,True,Vehicle Search,Arrest,True,30+ Min,False,RJ33IW9081

In [ ]:
traffic_stops.iloc[::5, :]

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,01-01-2020,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
5,01-01-2020,00:05:00,Canada,F,44,73,Other,Drunk Driving,Other,True,Vehicle Search,Ticket,False,16-30 Min,False,MH89ZF7676
10,01-01-2020,00:10:00,India,F,66,76,Black,Speeding,Signal,False,NaN,Ticket,False,30+ Min,True,UP67CQ9426
15,01-01-2020,00:15:00,USA,F,65,51,Hispanic,Other,DUI,True,Frisk,Ticket,False,16-30 Min,True,WB75TF1052
20,01-01-2020,00:20:00,USA,F,76,47,Hispanic,Signal Violation,Signal,False,NaN,Warning,False,0-15 Min,True,KA78HN8680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65515,15-02-2020,11:55:00,Canada,F,27,27,Other,Drunk Driving,Other,False,NaN,Arrest,True,16-30 Min,False,RJ82WS6374
65520,15-02-2020,12:00:00,USA,F,67,32,White,Speeding,Other,False,NaN,Arrest,False,30+ Min,True,UP10NB3599
65525,15-02-2020,12:05:00,Canada,F,74,61,Hispanic,Seatbelt,Seatbelt,True,Frisk,Ticket,False,16-30 Min,False,GJ41TB4105
65530,15-02-2020,12:10:00,India,M,34,72,White,Signal Violation,Seatbelt,True,NaN,Ticket,True,30+ Min,False,KA65MU9353
65535,15-02-2020,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328

In [ ]:
#Label based - select by row/column labels
traffic_stops.loc[3456, :]

stop_date                 03-01-2020
stop_time                   09:36:00
country_name                   India
driver_gender                      F
driver_age_raw                    52
driver_age                        62
driver_race                    Black
violation_raw               Seatbelt
violation                        DUI
search_conducted                True
search_type           Vehicle Search
stop_outcome                  Arrest
is_arrested                     True
stop_duration               0-15 Min
drugs_related_stop             False
vehicle_number            TN13TV3266
Name: 3456, dtype: object

In [ ]:
traffic_stops.loc[3456, 'violation_raw']

'Seatbelt'

In [ ]:
#condition
traffic_stops.loc[traffic_stops['driver_age']>75, :]

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
2,01-01-2020,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,01-01-2020,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
10,01-01-2020,00:10:00,India,F,66,76,Black,Speeding,Signal,False,NaN,Ticket,False,30+ Min,True,UP67CQ9426
24,01-01-2020,00:24:00,India,M,33,76,Hispanic,Signal Violation,Speeding,False,NaN,Warning,False,16-30 Min,False,MH83XS7688
38,01-01-2020,00:38:00,Canada,F,29,76,Hispanic,Speeding,Signal,True,Vehicle Search,Arrest,False,0-15 Min,False,RJ86OH2697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65512,15-02-2020,11:52:00,Canada,F,22,76,Other,Signal Violation,Signal,True,Vehicle Search,Arrest,True,16-30 Min,True,MH40QS1450
65513,15-02-2020,11:53:00,India,F,19,79,Black,Speeding,DUI,True,NaN,Ticket,False,30+ Min,True,UP83UH8771
65521,15-02-2020,12:01:00,India,M,24,78,Asian,Seatbelt,Seatbelt,False,Vehicle Search,Ticket,False,30+ Min,True,MH42PF3736
65522,15-02-2020,12:02:00,USA,M,71,80,Hispanic,Drunk Driving,Seatbelt,True,Vehicle Search,Arrest,True,30+ Min,False,RJ87IU6720
65529,15-02-2020,12:09:00,India,F,63,78,Black,Seatbelt,Seatbelt,True,NaN,Warning,False,0-15 Min,False,DL13IZ8119

In [ ]:
traffic_stops.loc[(traffic_stops['driver_age']>75) | (traffic_stops['driver_gender']=='F') , :]

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
2,01-01-2020,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,01-01-2020,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
5,01-01-2020,00:05:00,Canada,F,44,73,Other,Drunk Driving,Other,True,Vehicle Search,Ticket,False,16-30 Min,False,MH89ZF7676
6,01-01-2020,00:06:00,USA,F,80,70,White,Signal Violation,Speeding,False,Vehicle Search,Ticket,False,30+ Min,False,KA40AD3153
8,01-01-2020,00:08:00,USA,F,80,30,Hispanic,Other,Seatbelt,True,Frisk,Arrest,False,0-15 Min,True,DL50PO5101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65529,15-02-2020,12:09:00,India,F,63,78,Black,Seatbelt,Seatbelt,True,NaN,Warning,False,0-15 Min,False,DL13IZ8119
65533,15-02-2020,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,15-02-2020,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65536,15-02-2020,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,NaN,Warning,True,0-15 Min,True,KA24UZ8488
65537,15-02-2020,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,NaN,Ticket,True,16-30 Min,False,UP89PT2924

Data Cleaning

Check for missing values

In [ ]:
traffic_stops.isnull().sum()

stop_date                 0
stop_time                 0
country_name              0
driver_gender             0
driver_age_raw            0
driver_age                0
driver_race               0
violation_raw             0
violation                 0
search_conducted          0
search_type           21720
stop_outcome              0
is_arrested               0
stop_duration             0
drugs_related_stop        0
vehicle_number            0
dtype: int64